### ISSUE TITLE
Rename "Raw Elements" and "Raw Nodes" to just Elements and Nodes

### ISSUE THREAD

**Issue by philip-peterson** [philip-peterson/rust-rdom#6]
Right now, there are references to Raw nodes and Raw elements everywhere. While the intention (supporting a friendly interface as an alternative to the raw interface) I still believe is a good idea, we can just call this interface something like `mod friendly`, and then there will be `rdom::node::Node` and `rdom::node::friendly::Node`.

Related to #7

**Comment by maksimil** [comment]
I think that friendly interface could be added to raw nodes with impl blocks. Also, as you said, RawNodes should be renamed to Nodes to avoid confusion. I really don't see any reason to have wrappers.

**Comment by philip-peterson** [comment]
The friendly interface would be mostly to eliminate the need to constantly deference Arc's. I think removing them for now would be reasonable, though I suspect eventually we'll want to add them back because the Arcs will be a bit painful to use. The goal being to be as similar to using web_sys as possible. That said, it's possible I'm wrong and the Arcs will be fine.
